### PR TITLE
go/links lists all of the go links

### PR DESCRIPTION
**Pull request by mcfunley**
no paging or anything, just the most basic possible listing

### CODE REVIEW

**Comment by mcfunley** [comment]
solves #6 although if you already have a golink for /links you may be mad

**Comment by kellegous** [comment]
Arg, I think I totally screwed you up when I went mucking around last night. Let me rebase some things.

**Comment by mcfunley** [comment]
The diff looks ok to me, possible I screwed up resolving the conflict though

**Comment by kellegous** [comment]
I rebased everything. I went and made some meaningless changes last night, but it was easy to merge them.

**Comment by kellegous** [comment]
Closing as this is actually merged now.

**Pull request closed without merging**
